apiVersion: apps/v1
kind: Deployment
metadata:
  name: testkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testkube
  template:
    metadata:
      labels:
        app: testkube
    spec:
      containers:
        - name: app
          image: dinezmca/testkube:1
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
